version: '3'

networks:
  cluster_net:

services:

  core1:
    hostname: core1
    image: neo4j:3.5-enterprise
    networks:
      - cluster_net
    ports:
      - 7474:7474
      - 6477:6477
      - 7687:7687
    volumes:
      - $HOME/tmp/docker/cluster-simple/neo4j-core1/conf:/conf
      - $HOME/tmp/docker/cluster-simple/neo4j-core1/data:/data
      - $HOME/tmp/docker/cluster-simple/neo4j-core1/logs:/logs
      - $HOME/tmp/docker/cluster-simple/neo4j-core1/metrics:/metrics
      - $HOME/tmp/docker/cluster-simple/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_dbms_mode=HA
      - NEO4J_ha_server__id=1
      - NEO4J_ha_initial__hosts=core1:5001,core2:5001
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_http_listen__address=:7474
      - NEO4J_dbms_connector_https_listen__address=:6477
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_allow__upgrade=true
      - NEO4JLABS_PLUGINS=["apoc"]

  core2:
    hostname: core2
    image: neo4j:3.5-enterprise
    networks:
      - cluster_net
    ports:
      - 7475:7475
      - 6478:6478
      - 7688:7688
    volumes:
      - $HOME/tmp/docker/cluster-simple/neo4j-core2/conf:/conf
      - $HOME/tmp/docker/cluster-simple/neo4j-core2/data:/data
      - $HOME/tmp/docker/cluster-simple/neo4j-core2/logs:/logs
      - $HOME/tmp/docker/cluster-simple/neo4j-core2/metrics:/metrics
      - $HOME/tmp/docker/cluster-simple/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_dbms_mode=HA
      - NEO4J_ha_server__id=2
      - NEO4J_ha_initial__hosts=core1:5001,core2:5001
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_http_listen__address=:7475
      - NEO4J_dbms_connector_https_listen__address=:6478
      - NEO4J_dbms_connector_bolt_listen__address=:7688
      - NEO4J_dbms_allow__upgrade=true
      - NEO4JLABS_PLUGINS=["apoc"]


